version: "3.8"
services:
    stamurai:
        ports:
            - "8080:8090"
        expose:
            - "8090"
        build:
            context: .
            dockerfile: Dockerfile
        container_name: stamurai
        image: stamurai:latest
        working_dir: "/app"
        depends_on:
            - mongo
        links:
            - mongo
        networks:
            - stamurai
        volumes:
            - ./src:/app
            - /app/node_modules

    mongo:
        container_name: mongo
        image: mongo
        networks:
            - stamurai
        volumes:
            - ./dbData:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

networks:
    stamurai:
